---
# setup compose dir structure
- name: setup compose dir structure
  file:
    path: "{{ wp_project_dir }}/{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755
  with_items:
  - wordpress
  - db-data
  - nginx
  - logs/nginx
  tags:
    - dir_ops

- name: create docker-compose.yml file
  file:
    path: "{{ wp_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch
  tags:
    - file_ops

- name: deploy Docker Compose project for (Wordpress/MariaDB/Nginx containers)
  template:
    src: docker-compose.yml
    dest: "{{ wp_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - deploy_compose

- name: deploy WordPress Nginx virtual host
  template:
    src: wordpress.conf
    dest: "{{ wp_project_dir }}/nginx/wordpress.conf"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - gen_nginx

- name: Run docker-compose up
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ wp_project_dir }}"
  tags:
    - compose_run

# result output
- debug:
    msg:
      - "Dockerised wordpress setup completed."
      - "Access wordpress at: {{ inventory_hostname }}"
  tags:
    - result


