---
- name: Check if present netdata is present
  stat:
    path: "{{ netdata_install_dir }}/netdata"
  register: netdata_present
- debug: msg="netdata not installed"
  when: netdata_present.stat.exists == False
- debug: msg="netdata installed"
  when: netdata_present.stat.exists == True

- name: Install package dependencies
  apt:
    pkg: "{{ netdata_dependencies }}"
    state: present
  when: netdata_present.stat.exists == False
  tags:
    - netdata

- name: Clone or Pull from netdata repo
  git:
    repo: https://github.com/firehol/netdata.git
    depth: "1"
    dest: "{{ netdata_repo_dir }}"
  register: clone_or_pull
  tags:
    - netdata
- debug: var=clone_or_pull

- name: Build and install
  shell: "./netdata-installer.sh --install {{netdata_install_dir}} --dont-wait"
  args:
    chdir: "{{ netdata_repo_dir }}"
  when: clone_or_pull.changed == True
  tags:
    - netdata

# result output
- debug:
    msg:
      - "Netdata installation completed."
      - "Access netdata dashboard at: {{ inventory_hostname }}:19999"
  tags:
    - result
